<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>

        <!--Public AOT-->
        <PublishAot>true</PublishAot>
        <IsAotCompatible>true</IsAotCompatible>
        <InvariantGlobalization>true</InvariantGlobalization>
        <StripSymbols>true</StripSymbols>
        <BuiltInComInteropSupport>false</BuiltInComInteropSupport>
        <NoWarn>IL2026</NoWarn>
    </PropertyGroup>

	<ItemGroup>
        <!--This helps with theme dll-s trimming.
        If you will publish your application in self-contained mode with p:PublishTrimmed=true and it will use Fluent theme Default theme will be trimmed from the output and vice versa.
        https://github.com/AvaloniaUI/Avalonia/issues/5593 -->
        <TrimmableAssembly Include="Avalonia.Themes.Fluent" />
        <TrimmableAssembly Include="Avalonia.Themes.Default" />
    </ItemGroup>

    <ItemGroup>
        <None Remove=".gitignore" />
		<AvaloniaResource Include="Assets\**" />
        <TrimmerRootAssembly Include="AvaloniaAOT" />
    </ItemGroup>

    <ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.2" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<!--Compresse with UPX-->
        <!-- <PackageReference Include="PublishAotCompressed" Version="1.0.3" /> -->
    </ItemGroup>
</Project>
